### PR TITLE
Add support for FreeBSD v2

### PR DESCRIPTION
**Pull request by kennylevinsen**
Builds upon work from https://github.com/emersion/basu/pull/15.

The bus-cred test (due to heavy reliance on procfs) and a few subtests (due to just being errno tests) are skipped on FreeBSD, but other than that it seems to pass.

### CODE REVIEW

**Review by jbeich — COMMENTED** [review]
meson.build adds `-Wshadow`, confusing GCC which converts `mempcpy` into `__builtin_mempcpy` by default. Given Clang also supports `__builtin_mempcpy` maybe use it unconditionally or check via `__has_builtin`.
```diff
@@ -23,5 +23,9 @@
 #ifdef __FreeBSD__
+#if __has_builtin(mempcpy)
+#define mempcpy __builtin_mempcpy
+#else
 static void *mempcpy(void *dest, const void *src, size_t n) {
         return (char *)memcpy(dest, src, n) + n;
 }
+#endif
 #endif
```

To reproduce on amd64 (or any other architecture):
```
$ pkg install gcc10
$ export CC=gcc10 LDFLAGS="-Wl,-rpath,/usr/local/lib/gcc10"
$ meson setup _build
$ meson compile -C _build
```

**Comment by kennylevinsen** [comment]
@jbeich Thanks for testing! I have addressed your comments.

secure_getenv and mempcpy are now implemented more appropriately, and the credential test has been made to work if linprocfs is mounted (bus-creds relies heavily on Linux-style /proc/PID/status - although note that linprocfs is not required for general use).

**Comment by jbeich** [comment]
`--system` (default) socket appears to lack `/var` prefix. May need something like [seatd@884c1416b302](https://git.sr.ht/~kennylevinsen/seatd/commit/884c1416b302).
```
$ basuctl
<27>(../src/busctl/busctl.c:125) Failed to connect to bus: No such file or directory

$ dbus-run-session basuctl
<27>(../src/busctl/busctl.c:125) Failed to connect to bus: No such file or directory

$ truss basuctl |& fgrep system_bus
connect(3,{ AF_UNIX "/run/dbus/system_bus_socket" },30) ERR#2 'No such file or directory'

$ ls -1 /run/dbus/system_bus_socket /var/run/dbus/system_bus_socket
ls: /run/dbus/system_bus_socket: No such file or directory
/var/run/dbus/system_bus_socket
```

**Comment by kennylevinsen** [comment]
@jbeich Did you try on -CURRENT? I have only tested on -STABLE, but there is a thing or two hidden behind FreeBSD 13 `#if`'s.

**Comment by jbeich** [comment]
> Did you try on -CURRENT?

Yep. I only dogfood -CURRENT kernel but (during packaging) sometimes test runtime inside jails with old world/userland.

> EDIT: as for /var prefix, see #31

Indeed, `basuctl` works fine after applying that.

**Pull request merged**
