### PR TITLE
More cleanup

### PR DESCRIPTION
**Pull request by Hummer12007**
First commit drops totally unused code

Second drops OSC 8 suppport

### CODE REVIEW

**Comment by kennylevinsen** [comment]
This PR removes a few tests that I'd like to see if I can get re-enabled. They were disabled on grounds of using glib, but seems like they might be able to run without.

**Comment by Hummer12007** [comment]
>This PR removes a few tests that I'd like to see if I can get re-enabled. They were disabled on grounds of using glib, but seems like they might be able to run without.

Some of the tests I removed used dropped sd_event stuff.
Want me to revive the others?

**Comment by kennylevinsen** [comment]
The sd-event tests should just be dropped, but the more tests we can keep the better. The marshalling tests would be nice to have back.

**Comment by Hummer12007** [comment]
Done

**Review by kennylevinsen — APPROVED** [review]

**Comment by emersion** [comment]
Thanks!

**Pull request merged**
